// Bird Mahjong service worker: offline play after the first successful load.
//
// Consistency first. Every file the game needs is precached into ONE cache
// named after VERSION, and every request is answered from that cache. A page
// is therefore always served by a single, complete generation of files; old
// HTML never meets new JavaScript.
//
// Safe updates. VERSION is a hash of the precached files' contents, written
// by `npm run build:sw` (tests fail if it's stale), so any change to any
// cached file produces a new service worker:
//   1. The page registers with updateViaCache: "none" and checks for an update
//      on every load and whenever it comes back to the foreground.
//   2. A new worker precaches the new version into a NEW cache (bypassing the
//      HTTP cache) while the old one keeps serving. If any file fails, the
//      install fails and nothing changes.
//   3. The new worker then waits. The page offers "Refresh"; tapping it
//      autosaves the board and tells the worker to take over (SKIP_WAITING),
//      and the page reloads once on controllerchange. If the player ignores
//      it, the new version starts on the next cold start (all tabs closed).
//   4. On activate, caches from older versions are deleted.
//
// Paths are relative to the worker's scope, so the same file works at a
// domain root and under /Bird-Mahjong/ on GitHub Pages.

const VERSION = "aab44907726c";
const CACHE_PREFIX = "bird-mahjong-";
const CACHE = `${CACHE_PREFIX}${VERSION}`;
const RUNTIME = `${CACHE_PREFIX}runtime`;

// BEGIN PRECACHE (generated by tools/build-sw.mjs — do not edit by hand)
const PRECACHE = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "css/app.css",
  "js/app.js",
  "js/background.js",
  "js/best-scores.js",
  "js/config.js",
  "js/game/birds.js",
  "js/game/game.js",
  "js/game/generator.js",
  "js/game/geometry.js",
  "js/game/rng.js",
  "js/game/rules.js",
  "js/game/save-format.js",
  "js/game/score.js",
  "js/pwa.js",
  "js/saved-game.js",
  "js/settings.js",
  "js/storage.js",
  "js/ui/bird-names.js",
  "js/ui/board-view.js",
  "js/ui/game-controller.js",
  "js/ui/sound.js",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "assets/tiles-sm/01-bald-eagle.webp",
  "assets/tiles-sm/02-osprey.webp",
  "assets/tiles-sm/03-red-tailed-hawk.webp",
  "assets/tiles-sm/04-peregrine-falcon.webp",
  "assets/tiles-sm/05-barred-owl.webp",
  "assets/tiles-sm/06-great-horned-owl.webp",
  "assets/tiles-sm/07-american-crow.webp",
  "assets/tiles-sm/08-common-raven.webp",
  "assets/tiles-sm/09-blue-jay.webp",
  "assets/tiles-sm/10-northern-cardinal.webp",
  "assets/tiles-sm/11-american-robin.webp",
  "assets/tiles-sm/12-black-capped-chickadee.webp",
  "assets/tiles-sm/13-tufted-titmouse.webp",
  "assets/tiles-sm/14-pileated-woodpecker.webp",
  "assets/tiles-sm/15-belted-kingfisher.webp",
  "assets/tiles-sm/16-great-blue-heron.webp",
  "assets/tiles-sm/17-wood-duck.webp",
  "assets/tiles-sm/18-wild-turkey.webp",
  "assets/tiles-sm/19-canada-goose.webp",
  "assets/tiles-sm/20-ruby-throated-hummingbird.webp",
  "assets/tiles-md/01-bald-eagle.webp",
  "assets/tiles-md/02-osprey.webp",
  "assets/tiles-md/03-red-tailed-hawk.webp",
  "assets/tiles-md/04-peregrine-falcon.webp",
  "assets/tiles-md/05-barred-owl.webp",
  "assets/tiles-md/06-great-horned-owl.webp",
  "assets/tiles-md/07-american-crow.webp",
  "assets/tiles-md/08-common-raven.webp",
  "assets/tiles-md/09-blue-jay.webp",
  "assets/tiles-md/10-northern-cardinal.webp",
  "assets/tiles-md/11-american-robin.webp",
  "assets/tiles-md/12-black-capped-chickadee.webp",
  "assets/tiles-md/13-tufted-titmouse.webp",
  "assets/tiles-md/14-pileated-woodpecker.webp",
  "assets/tiles-md/15-belted-kingfisher.webp",
  "assets/tiles-md/16-great-blue-heron.webp",
  "assets/tiles-md/17-wood-duck.webp",
  "assets/tiles-md/18-wild-turkey.webp",
  "assets/tiles-md/19-canada-goose.webp",
  "assets/tiles-md/20-ruby-throated-hummingbird.webp",
];
// END PRECACHE

const scoped = (path) => new URL(path, self.registration.scope).href;

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // cache: "reload" skips the HTTP cache so a new version never mixes in
      // stale files that GitHub Pages' CDN or the browser still hold.
      cache.addAll(PRECACHE.map((path) => new Request(scoped(path), { cache: "reload" })))
    )
  );
  // No skipWaiting here: an update waits until the player chooses to refresh
  // (or next cold start), so a running game is never swapped mid-session.
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(
        keys.filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE && key !== RUNTIME).map((key) => caches.delete(key))
      );
      // Runtime-cached extras (e.g. the tile gallery) may be from an older
      // version; start them fresh too.
      await caches.delete(RUNTIME);
      await self.clients.claim();
    })()
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
  if (event.data && event.data.type === "GET_VERSION") event.source?.postMessage({ type: "VERSION", version: VERSION });
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;

  // Game navigations (any query, e.g. ?seed=5) get the cached app shell.
  if (request.mode === "navigate" && isAppShell(url)) {
    event.respondWith(fromCache(scoped("./")).then((hit) => hit || fetch(request)));
    return;
  }

  event.respondWith(
    (async () => {
      const cached = await caches.match(request, { cacheName: CACHE, ignoreSearch: true });
      if (cached) return cached;
      // Not part of the game (e.g. tiles.html, full-size PNGs): network first,
      // keeping a copy so it also works offline after one visit.
      try {
        const response = await fetch(request);
        if (response.ok) (await caches.open(RUNTIME)).put(request, response.clone());
        return response;
      } catch (error) {
        const fallback = await caches.match(request, { cacheName: RUNTIME, ignoreSearch: true });
        if (fallback) return fallback;
        throw error;
      }
    })()
  );
});

function isAppShell(url) {
  const path = url.href.slice(self.registration.scope.length).split(/[?#]/)[0];
  return path === "" || path === "index.html";
}

async function fromCache(href) {
  return caches.match(href, { cacheName: CACHE });
}
