#!/usr/bin/env node
// Regenerate the precache list and VERSION in sw.js.
//
// The list is built from the files on disk (so a new module or tile can't be
// forgotten), and VERSION is a hash of every precached file plus the worker's
// own code. Any change to anything the game caches therefore ships as a new
// service worker with a new cache: the safe update path in sw.js.
//
// Usage:
//   node tools/build-sw.mjs          rewrite sw.js
//   node tools/build-sw.mjs --check  exit 1 if sw.js is out of date (tests use this)

import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SW = path.join(ROOT, "sw.js");

const list = (dir, ext) =>
  fs.readdirSync(path.join(ROOT, dir))
    .filter((f) => f.endsWith(ext))
    .sort()
    .map((f) => `${dir}/${f}`);

const walk = (dir) =>
  fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(`${dir}/${e.name}`) : e.name.endsWith(".js") ? [`${dir}/${e.name}`] : []);

/** Everything the game needs to run offline. "./" is the app shell URL itself. */
export function precacheList() {
  return [
    "./",
    "index.html",
    "manifest.webmanifest",
    "css/app.css",
    ...walk("js").filter((f) => f !== "js/gallery.js").sort(),
    ...list("icons", ".png"),
    ...list("assets/tiles-sm", ".webp"),
    ...list("assets/tiles-md", ".webp"),
    // INSPIRE branding: the logo (start screen, game footer) and the intro
    // video (js/ui/intro.js), both copied from officialinspire/DEJA-VU-MEMORY-GAME.
    "logo.png",
    "inspiresoftwareintro.mp4",
    // Music (root MP3s, streamed by js/ui/music.js).
    ...fs.readdirSync(ROOT).filter((f) => f.endsWith(".mp3")).sort(),
    // Optional recorded audio (see AUDIO_FILES in js/config.js).
    ...(fs.existsSync(path.join(ROOT, "assets/audio"))
      ? fs.readdirSync(path.join(ROOT, "assets/audio")).filter((f) => /\.(mp3|m4a|ogg|opus|wav)$/.test(f)).sort().map((f) => `assets/audio/${f}`)
      : []),
  ];
}

const BEGIN = "// BEGIN PRECACHE (generated by tools/build-sw.mjs — do not edit by hand)";
const END = "// END PRECACHE";

/** sw.js with the given list and version filled in. */
export function renderSw(source, files, version) {
  const block = `${BEGIN}\nconst PRECACHE = [\n${files.map((f) => `  ${JSON.stringify(f)},`).join("\n")}\n];\n${END}`;
  const start = source.indexOf(BEGIN);
  const end = source.indexOf(END) + END.length;
  if (start < 0 || end < END.length) throw new Error("sw.js is missing the PRECACHE markers");
  return (source.slice(0, start) + block + source.slice(end)).replace(/const VERSION = "[^"]*";/, `const VERSION = "${version}";`);
}

/** Hash of every precached file and of the worker's code (with VERSION blanked). */
export function computeVersion(source, files) {
  const hash = createHash("sha256");
  hash.update(renderSw(source, files, ""));
  for (const f of files) {
    if (f === "./") continue;
    hash.update(`\0${f}\0`);
    hash.update(fs.readFileSync(path.join(ROOT, f)));
  }
  return hash.digest("hex").slice(0, 12);
}

export function buildSw() {
  const source = fs.readFileSync(SW, "utf8");
  const files = precacheList();
  for (const f of files) {
    if (f !== "./" && !fs.existsSync(path.join(ROOT, f))) throw new Error(`missing ${f}`);
  }
  const version = computeVersion(source, files);
  return { source, next: renderSw(source, files, version), files, version };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { source, next, files, version } = buildSw();
  if (process.argv.includes("--check")) {
    if (source !== next) {
      console.error("sw.js is out of date: run `npm run build:sw` and commit the result.");
      process.exit(1);
    }
    console.log(`sw.js up to date (version ${version}, ${files.length} files)`);
  } else {
    fs.writeFileSync(SW, next);
    const bytes = files.filter((f) => f !== "./").reduce((n, f) => n + fs.statSync(path.join(ROOT, f)).size, 0);
    console.log(`sw.js: version ${version}, ${files.length} files, ${(bytes / 1024).toFixed(0)} KB precached`);
  }
}
